// <auto-generated />
using System;
using BillEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillEntites.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210918210113_FirstDB")]
    partial class FirstDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BillEntity.Model.BILDTL", b =>
                {
                    b.Property<Guid>("DTLCOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BILCOD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BILPRC")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ITMCOD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ITMQTY")
                        .HasColumnType("int");

                    b.HasKey("DTLCOD");

                    b.HasIndex("BILCOD");

                    b.HasIndex("ITMCOD");

                    b.ToTable("Bildtls");
                });

            modelBuilder.Entity("BillEntity.Model.BILHDR", b =>
                {
                    b.Property<Guid>("BILCOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BILDAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("BILIMG")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<decimal>("BILPRC")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VNDCOD")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BILCOD");

                    b.HasIndex("VNDCOD");

                    b.ToTable("Bilhdrs");
                });

            modelBuilder.Entity("BillEntity.Model.ITMDTL", b =>
                {
                    b.Property<Guid>("ITMCOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ITMNAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("ITMPRC")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ITMCOD");

                    b.ToTable("Itmdtls");
                });

            modelBuilder.Entity("BillEntity.Model.VNDDTL", b =>
                {
                    b.Property<Guid>("VNDCOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VNDNAM")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("VNDCOD");

                    b.ToTable("Vnddtls");
                });

            modelBuilder.Entity("BillEntity.Model.BILDTL", b =>
                {
                    b.HasOne("BillEntity.Model.BILHDR", "BILHDR")
                        .WithMany("bildtl")
                        .HasForeignKey("BILCOD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillEntity.Model.ITMDTL", "ITMDTL")
                        .WithMany("bildtl")
                        .HasForeignKey("ITMCOD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BillEntity.Model.BILHDR", b =>
                {
                    b.HasOne("BillEntity.Model.VNDDTL", "VNDDTL")
                        .WithMany("bilhdr")
                        .HasForeignKey("VNDCOD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
